baseURL = "https://santiagopastorino.com"
title = "Santiago Pastorino"
theme = "beautifulhugo"
enableGitInfo = true
footnoteReturnLinkContents = "↩"
paginate = 7
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = "UA-89777501-1"

[frontmatter]
  date = [":filename", ":default"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  subtitle = "WyeWorks Co-Founder & Rust Compiler Team Contributor"
  logo = "images/santiago.jpg"
  favicon = "images/favicon.ico"
  commit = false
  showRelatedPosts = true
  useHLJS = true
  rss = true

[author]
  name = "Santiago Pastorino"
  email = "spastorino@gmail.com"
  github = "spastorino"
  twitter = "spastorino"

[menu]

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "about"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3

[caches]

[caches.images]
dir = ":resourceDir/_gen"
maxAge = -1

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = -1
